# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

notify:
  - name: ALL_DEVICES
    platform: group
    services:
      - service: mobile_app_titing_galiiiiiit
      - service: mobile_app_l337s_ipad
